version: '3.8'

services:
  back-end:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    ports:
      - "5252:5252"
    volumes:
      - ./back-end:/app
    container_name: back-end

  front-end:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - ./front-end:/var/www/html
    container_name: front-end
